language: node_js
node_js:
  - 10
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn travis
cache:
  yarn: true
